name: CI

on:
  push:
    branches-ignore:
      - cpp-rewrite
      - horizon-os
      - refactor
    paths-ignore:
      - ".gitignore"
      - ".github/*"
      - "**.md"
      - "LICENSE"
      - "drshorizon/**"
      - "res/**"
  workflow_dispatch:
  release:
    types:
      - released

defaults:
  run:
    shell: bash

env:
  VERSION: "0.102.0"

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: Linux x86_64
            os: ubuntu-latest
            channel: stable
            target: x86_64-unknown-linux-gnu
            target_name: linux-x64
            arch_name: x86_64

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install libasound2-dev libudev-dev \
            libgl1-mesa-dev libxext-dev \
            libwayland-dev libxkbcommon-dev libdecor-0-dev

      - name: Set version
        id: set_version
        run: |
          echo "version=${{ env.VERSION }}-${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
          echo "channel=nightly" >> $GITHUB_OUTPUT

      - name: Setup rust toolchain
        run: |
          rustup default ${{ matrix.channel }}
          rustup target add ${{ matrix.target }}

          rustc -vV
          cargo -vV

      - name: Build
        run: |
          if [ -z "${{ steps.set_version.outputs.version }}" ]; then
            echo "version is not set"
            exit 1
          fi

          export DRS_BUILD_VERSION_OVERRIDE="${{ steps.set_version.outputs.version }}"

          mkdir release

          RUSTFLAGS="-C link-args=-s" CARGO_INCREMENTAL=1 cargo build -vv --release --locked --bin doukutsu-rs --target ${{ matrix.target }}
          cp -a ./target/${{ matrix.target }}/release/doukutsu-rs release/doukutsu-rs.${{ matrix.arch_name }}.elf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: doukutsu-rs_${{ matrix.target_name }}
          path: ./release/*
          if-no-files-found: error
